### ISSUE TITLE
Can't resolve InjectionProvider in App class

### ISSUE THREAD

**Issue by aplatypus** [AdamBien/airhacks-control#1]
Hi Adam,

I saw your demo of this example using **afterburner.fx**.  I wanted to see how it works and performs bindings, etc.  So I just downloaded the master and tried to build it with maven using netbeans.

Everything compiled after I resolved a couple of dependencies.  The main thing was
- http://mvnrepository.com/artifact/com.airhacks/afterburner.fx/1.5.1

There is one error in the main **App** class for _stop()_.

```
    @Override
    public void stop() throws Exception {
        InjectionProvider.forgetAll();
    }
```

**InjectionProvider** is unresolved.  

I then took a look at your **followme.fx** example, as the simplest example possible.  It uses a different structure and an **Injector** class.

I thought you might like to keep the **airhacks-control** example inline with changes in the libraries.  But also I'd like to get it running so I can test these ideas for myself.  I'm hoping there's a one (or 3) line change that will get it going quickly.

Many thanks,
     William

**Comment by AdamBien** [comment]
A good catch! Thanks for testing. I updated and tested airhacks-control with the recent afterburner. All the dependencies are also updated. Thanks!
