### ISSUE TITLE
shade plugin dependency inconsistiency

### ISSUE THREAD

**Issue by aplatypus** [AdamBien/airhacks-control#2]
Hi, I downloaded the revised **airhacks-control** to build with Netbeans 8 (JDK 8u05).  I had conflicts in the maven build.  Out of date dependencies or conflicts with other modules in my local repository.

Since it is a JavaFX project, I used a netbeans maven JavaFX Application project as a skeleton and deleted the generated files keeping the project config and POM file.

After minimal changes builds fine.  Test scripts report a PASS and running the main **_App**_ looks to me like like the program is operating OK.  

I thought I'd let you know about inconsistencies.  The maven build should work with any IDE or the command line, so I think it is worth taking a look at those things.  It is simple enough to get working.  I just like eliminating warnings and inconsistencies in basic areas like builds where something can get lost in a volume of output.

Regards,

   William

---

**POM.xml**
Properties (from netbeans when selected JDK 1.8)

```
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

```

Dependencies
- changed _eclipselink_ to: <version>**2.5.1**</version> due to shade I believe.

```
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>eclipselink</artifactId>
            <version>2.5.1</version>
        </dependency>
```

Plugins
- excluded _afterburner.fx_ from: <goal>**shade**</goal>

```
                <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <excludes>
                                    <exclude>junit:junit</exclude>
                                    <exclude>afterburner.fx</exclude>
                                </excludes>
                            </artifactSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by AdamBien** [comment]
Thanks! First I could not replicate this, then upgraded to maven 3.2.1 and recognized the issue. All dependencies are updated.
